### Numpy

In [1]:
import numpy as np

In [2]:
A = np.array([3, 29, 82])
B = np.array(((3., 29, 82), (10, 18, 64)))
C = np.array([[3, 29, 82],
             [10, 18, 64]], dtype = float)
D = np.array([3, 29, 'Park'])
E = np.array([[3], [29], [82]])

In [3]:
print(A.ndim, A.size, A.shape, A.dtype)

1 3 (3,) int32


In [4]:
print(B.ndim, B.size, B.shape, B.dtype)
print(C.ndim, C.size, C.shape, C.dtype)
print(D.ndim, D.size, D.shape, D.dtype)
print(E.ndim, E.size, E.shape, E.dtype)

2 6 (2, 3) float64
2 6 (2, 3) float64
1 3 (3,) <U11
2 3 (3, 1) int32


In [6]:
arr = np.zeros((3, ))
arr

array([0., 0., 0.])

In [10]:
arr2 = np.ones((3, 2), dtype = int)
arr2

array([[1, 1],
       [1, 1],
       [1, 1]])

In [13]:
arr3 = np.eye(3, dtype = int)
arr3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
arr4 = np.empty((3, 2))  #forms an array without initializing
print(arr4)

arr5 = np.empty((0, 9)) 
print(arr5)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[]


In [35]:
arr6 = np.arange(0, 10, 0.2)
arr6

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [39]:
arr7 = np.linspace(0, 1, 5)
arr7

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [105]:
arr8 = np.random.randint(((2, 3, 4), (1, 3, 10)))
arr8

array([[1, 2, 0],
       [0, 1, 4]])

In [108]:
my_arr = np.array(((3., 29, 82), (10, 18, 84)))

my_arr[1][1]

18.0

In [111]:
my_arr[1, :2]

array([10., 18.])

In [112]:
my_arr > 15

array([[False,  True,  True],
       [False,  True,  True]])

In [113]:
my_arr[my_arr > 10]

array([29., 82., 18., 84.])

In [115]:
my_arr[my_arr > 15] = 100
my_arr

array([[  3., 100., 100.],
       [ 10., 100., 100.]])